import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import CheckOutButton from "@/components/CheckOutButton";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { BookingProvider } from "@/context/BookingContext";
import { SearchProvider } from "@/context/SearchContext";
import HeroWrapper from "@/components/HeroWrapper";
import AuthContextProvider from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Travel Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <AuthContextProvider>
        <SearchProvider>
          <BookingProvider>
            <Header />
            <HeroWrapper />
            <main className="flex-grow">{children}</main>
            <CheckOutButton />
            <Toaster position="top-right" />
            <Footer />
          </BookingProvider>
        </SearchProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
