import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import CheckOutButton from "@/components/CheckOutButton";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { SearchProvider } from "@/context/SearchContext";
import Hero from "@/components/Hero";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Travel Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <SearchProvider>
          <Header />
          {/* Hero Section */}
          <Hero />
          <main className="flex-grow">{children}</main>
          <CheckOutButton />
          <Toaster position="top-right" />
          <Footer />
        </SearchProvider>
      </body>
    </html>
  );
}
